### ISSUE TITLE
Naming of entries unclear

### ISSUE THREAD

**Issue by gernert** [TinkaPlugin/Tinka#6]
When creating a new plugin/theme you have to fill in a 'Plugin/Theme Title'.
When repackaging, these 'Plugin/Theme Title' cannot be found anymore as such.
In case of a theme, 'Name' (mandatory for a theme) contains 'Theme Title' while in case of a plugin 'Name' is empty.

**Comment by TinkaPlugin** [comment]
Similiarly to my answer in #5, when I introduced this feature, I wanted to give these fields proper names that make it clear what it does, since the original way TW handled the `name` and `description` field of plugins and themes differently turned out to be confusing for beginners.
After creating the plugin though, I do want to give people full access to all of the relevant fields with their internal names that a plugin can possibly have and not rename/hide things depending on the plugin type.

This little quirk is however mentioned and described in the documentation of the plugin, so right now, I wouldn't have any ideas on how to handle this differently. Do you have any suggestions?

**Comment by gernert** [comment]
Hi Andreas,

I think the documentation is confusing as well. The names of the entry fields are explained (__Author__, __Source__, __Dependentes__, ...) but instead of __Theme Title__ the documentation mentions __Name__:

*__Name:__ For themes, this contains the theme title that is shown in the control panel.*

May be better to write it the other way around:

__Theme Title:__ the __name__ of the theme as shown in the control panel and in the theme dropdown menu.

For the  Tinka packer names maybe some extra 'explanation' for the names of the entry fields:

__Plugin Title:__
(= description)

__Theme Title:__
(= name)

What do you think?

**Comment by TinkaPlugin** [comment]
I hope this issue is now solved with the newest version.
